import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Layout } from '@/Layout/Layout'
import { setupStore } from '@/Store/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })
const store = setupStore()

//@ts-ignore
export default function Home({data}) {
    return (
        <>
            <Head>
                <title>EcoLifestyle</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Provider store={store}>
                <Layout newsData={data}/>
            </Provider>
        </>
    )
}

export const getStaticProps = async () => {
    const apiKey = 'b09aa1da7a8d45a7b5044d9b174a0eae';
    const url = `https://newsapi.org/v2/everything?q=(ecology)&language=en&apiKey=${apiKey}`;

    const data = await fetch(url).then(response => response.json())


    return{
        props: {
            data
        }
    }
}